#!/usr/bin/env python3
"""build_bundle.py — generate data/tickers-bundle.js with all per-ticker data
inlined so the dashboard works on file:// (no fetch() needed).

Runs after generate_data.py. Reads every JSON in data/{companies,narratives,
ta_levels,factset,options}/*.json and emits:

    window.TICKER_DATA_BUNDLE = JSON.parse('...');

The companion app.js looks for this first in loadTicker() before falling back
to fetch(). With this in place, the dashboard renders fully even when opened
directly as a local file with no HTTP server.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
DIRS = ("companies", "narratives", "ta_levels", "factset", "options")
OUT = DATA / "tickers-bundle.js"


def main() -> int:
    bundle: dict[str, dict[str, object]] = {}
    counts = {d: 0 for d in DIRS}
    for d in DIRS:
        dir_path = DATA / d
        if not dir_path.exists():
            continue
        for jf in sorted(dir_path.glob("*.json")):
            ticker = jf.stem
            bundle.setdefault(ticker, {})[d] = json.loads(jf.read_text(encoding="utf-8"))
            counts[d] += 1

    # Also scan assets/charts/{TICKER}/*.png and bundle the list of available
    # chart filenames so the renderer can emit <img> tags without 404 noise.
    charts_root = ROOT / "assets" / "charts"
    chart_counts = 0
    if charts_root.exists():
        for ticker_dir in charts_root.iterdir():
            if not ticker_dir.is_dir():
                continue
            ticker = ticker_dir.name
            # Exclude chart_00.png placeholder (1KB stub that exists in some dirs)
            files = sorted(
                p.name for p in ticker_dir.glob("*.png")
                if p.name != "chart_00.png"
            )
            if files:
                bundle.setdefault(ticker, {})["charts"] = files
                chart_counts += len(files)
    print(f"  Charts indexed: {chart_counts} PNG files across {sum(1 for v in bundle.values() if 'charts' in v)} tickers")

    raw = json.dumps(bundle, separators=(",", ":"), ensure_ascii=False)
    # Escape for embedding in a single-quoted JS string literal
    escaped = raw.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "")
    header = (
        "// Generated by build_bundle.py — DO NOT EDIT BY HAND.\n"
        "// Inlines every per-ticker JSON so the dashboard works on file://\n"
        "// without any fetch() calls. Parsed at load via JSON.parse (PRD §5.2).\n"
    )
    body = f"window.TICKER_DATA_BUNDLE = JSON.parse('{escaped}');\n"
    OUT.write_text(header + body, encoding="utf-8")
    size = OUT.stat().st_size
    tickers = sorted(bundle.keys())
    print(f"Wrote {OUT} ({size:,} bytes)")
    print(f"  Tickers: {len(tickers)} → {tickers}")
    print(f"  Per-dir counts: {counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
