"""Serialize a validated `DashboardPayload` to canonical JSON and to the
local-safe JS wrapper.

Per PRD §5.2 and §13: the JS file must be `window.DASHBOARD_DATA =
JSON.parse('<escaped JSON string>');` — a raw object literal is rejected.
The escape must survive every byte sequence JSON can produce, including the
two characters that are valid in JSON strings but break a JS string literal
(U+2028 LINE SEPARATOR, U+2029 PARAGRAPH SEPARATOR).

Single responsibility: serialization. No validation, no I/O target selection
beyond the configured paths.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .config import EMIT_JS, EMIT_JSON
from .schema import DashboardPayload

# ---------------------------------------------------------------------------
# Escape map for JS single-quoted string literal
# ---------------------------------------------------------------------------

# Order matters: backslash first so we don't double-escape the escapes we
# introduce.
_JS_ESCAPES = (
    ("\\", "\\\\"),
    ("'",  "\\'"),
    ("\r", "\\r"),
    ("\n", "\\n"),
    ("\t", "\\t"),
    (" ", "\\u2028"),  # LINE SEPARATOR — valid in JSON, breaks JS string
    (" ", "\\u2029"),  # PARAGRAPH SEPARATOR — same
    ("\b", "\\b"),
    ("\f", "\\f"),
)


def js_escape_for_string_literal(s: str) -> str:
    """Escape a JSON string so it can be embedded in a single-quoted JS literal.

    The output is intended to sit inside `'...'` and be parsed by JSON.parse.
    """
    out = s
    for src, dst in _JS_ESCAPES:
        out = out.replace(src, dst)
    return out


# ---------------------------------------------------------------------------
# Canonical JSON
# ---------------------------------------------------------------------------

def payload_to_canonical_json(payload: DashboardPayload) -> str:
    """Render `payload` to a stable, deterministic JSON string.

    Keys are sorted, separators are tight, datetimes are ISO-8601 Z. This is
    what gets written to `dashboard-data.json` and what gets escaped into
    `dashboard-data.js`.
    """
    obj: dict[str, Any] = json.loads(
        payload.model_dump_json(exclude_none=False, by_alias=False)
    )
    # `model_dump_json` emits datetimes as ISO-8601 — make sure it ends with Z
    if isinstance(obj.get("generatedAt"), str):
        ts = obj["generatedAt"]
        if ts.endswith("+00:00"):
            obj["generatedAt"] = ts.replace("+00:00", "Z")
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


# ---------------------------------------------------------------------------
# JS wrapper
# ---------------------------------------------------------------------------

_JS_HEADER = (
    "// Generated by generate_data.py — DO NOT EDIT BY HAND.\n"
    "// Data is parsed at load via JSON.parse for speed + safety (PRD §5.2 / §13).\n"
    "// Raw object literals are prohibited.\n"
)


def payload_to_js_wrapper(payload: DashboardPayload) -> str:
    """Render the `window.DASHBOARD_DATA = JSON.parse('...');` form."""
    canonical = payload_to_canonical_json(payload)
    escaped = js_escape_for_string_literal(canonical)
    return f"{_JS_HEADER}window.DASHBOARD_DATA = JSON.parse('{escaped}');\n"


# ---------------------------------------------------------------------------
# File writers
# ---------------------------------------------------------------------------

def write_emitted_files(
    payload: DashboardPayload,
    *,
    json_path: Path | None = None,
    js_path: Path | None = None,
) -> tuple[Path, Path]:
    """Write both `dashboard-data.json` and `dashboard-data.js`.

    Returns (json_path, js_path). The paths are guard-checked by
    `safeguards.py` — this function only writes; it does not verify the
    write surface.
    """
    json_p = json_path or EMIT_JSON
    js_p = js_path or EMIT_JS

    json_p.parent.mkdir(parents=True, exist_ok=True)
    js_p.parent.mkdir(parents=True, exist_ok=True)

    json_p.write_text(
        json.dumps(
            json.loads(payload.model_dump_json(exclude_none=False)),
            sort_keys=True, indent=2, ensure_ascii=False,
        ) + "\n",
        encoding="utf-8",
    )
    js_p.write_text(payload_to_js_wrapper(payload), encoding="utf-8")
    return json_p, js_p


# ---------------------------------------------------------------------------
# Round-trip helper (used in tests + verify.py)
# ---------------------------------------------------------------------------

def round_trip_check(js_text: str) -> dict[str, Any]:
    """Strip the wrapper from a `dashboard-data.js` file and JSON-decode it.

    The returned dict should be deep-equal to what `payload_to_canonical_json`
    produced. Raises ValueError if the wrapper isn't in the JSON.parse form.
    """
    # Find the literal — be precise to catch raw-object-literal regressions.
    marker = "window.DASHBOARD_DATA = JSON.parse('"
    start = js_text.find(marker)
    if start < 0:
        raise ValueError(
            "dashboard-data.js does not contain the required "
            "`window.DASHBOARD_DATA = JSON.parse('...')` form"
        )
    start += len(marker)
    # Find the closing `');` — walk forward respecting our escape rules.
    i = start
    while i < len(js_text):
        c = js_text[i]
        if c == "\\":
            i += 2
            continue
        if c == "'":
            break
        i += 1
    if i >= len(js_text):
        raise ValueError("dashboard-data.js JSON literal is not properly closed")
    escaped = js_text[start:i]

    # Unescape with a proper left-to-right scanner. Naive `str.replace` in
    # reverse order is incorrect: e.g. `\\\\b...` (escaped-backslash followed
    # by a literal `b`) would otherwise match `\\b` (escaped backspace) and
    # corrupt the byte stream. PRD §5.2 requires byte-exact round-trip.
    unescaped_chars: list[str] = []
    j = 0
    L = len(escaped)
    while j < L:
        c = escaped[j]
        if c != "\\":
            unescaped_chars.append(c)
            j += 1
            continue
        # Backslash: consume the escape sequence.
        if j + 1 >= L:
            raise ValueError("trailing backslash in JS string literal")
        nxt = escaped[j + 1]
        if nxt == "\\":
            unescaped_chars.append("\\")
            j += 2
        elif nxt == "'":
            unescaped_chars.append("'")
            j += 2
        elif nxt == "n":
            unescaped_chars.append("\n")
            j += 2
        elif nxt == "r":
            unescaped_chars.append("\r")
            j += 2
        elif nxt == "t":
            unescaped_chars.append("\t")
            j += 2
        elif nxt == "b":
            unescaped_chars.append("\b")
            j += 2
        elif nxt == "f":
            unescaped_chars.append("\f")
            j += 2
        elif nxt == "u":
            # \uXXXX 4-hex unicode escape (e.g.  ,  )
            if j + 6 > L:
                raise ValueError("truncated \\uXXXX escape in JS string literal")
            hex4 = escaped[j + 2 : j + 6]
            unescaped_chars.append(chr(int(hex4, 16)))
            j += 6
        else:
            # Unknown escape — keep the backslash + next char verbatim; this
            # lets JSON.parse see a JSON-level escape like \" or \\u00XX
            # passed through unchanged.
            unescaped_chars.append("\\")
            unescaped_chars.append(nxt)
            j += 2
    unescaped = "".join(unescaped_chars)
    result: dict[str, Any] = json.loads(unescaped)
    return result
